{
 "title": "Harvester VM Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "count", "label": "count", "query": "5, 10, 20" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (avg(rate(kubevirt_vmi_vcpu_seconds_total[5m])) by (domain, name)) / 1000)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, ((kubevirt_vmi_memory_available_bytes - kubevirt_vmi_memory_unused_bytes) / kubevirt_vmi_memory_available_bytes))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage Read Traffic Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_storage_read_traffic_bytes_total[5m]))) ",
     "legendFormat": "{{name}}: {{drive}}"
    }
   ]
  },
  {
   "title": "Storage Write Traffic Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_storage_write_traffic_bytes_total[5m]))) ",
     "legendFormat": "{{name}}: {{drive}}"
    }
   ]
  },
  {
   "title": "Network Receive Bits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_network_receive_bytes_total[5m])*8))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Bits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "topk(${count}, (irate(kubevirt_vmi_network_transmit_bytes_total[5m])*8))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Receive Packets (2h)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(${count}, (delta(kubevirt_vmi_network_receive_packets_total[2h])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmit Packets (2h)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(${count}, (delta(kubevirt_vmi_network_transmit_packets_total[2h])))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}
{
 "title": "Harvester VM Info Detail",
 "description": "Harvester VM Info Detail",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_vcpu_seconds_total, namespace)"
    }
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(kubevirt_vmi_vcpu_seconds_total{namespace=\"$namespace\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg(rate(kubevirt_vmi_vcpu_seconds_total{namespace=\"$namespace\", name=\"$vm\"}[5m])) by (domain, name)) / 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum((kubevirt_vmi_memory_available_bytes{namespace=\"$namespace\", name=\"$vm\"} -kubevirt_vmi_memory_unused_bytes{namespace=\"$namespace\", name=\"$vm\"})/kubevirt_vmi_memory_available_bytes{namespace=\"$namespace\", name=\"$vm\"})"
    }
   ]
  },
  {
   "title": "IO Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_write_traffic_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-write"
    }
   ]
  },
  {
   "title": "IO Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_read_times_seconds_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_write_times_seconds_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-write"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_storage_iops_read_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-read"
    },
    {
     "expr": "irate(kubevirt_vmi_storage_iops_write_total{namespace=\"$namespace\", name=\"$vm\"}[5m])",
     "legendFormat": "{{drive}}-writ"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(kubevirt_vmi_network_receive_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-receive"
    },
    {
     "expr": "irate(kubevirt_vmi_network_transmit_bytes_total{namespace=\"$namespace\", name=\"$vm\"}[5m])*8",
     "legendFormat": "{{interface}}-transmit"
    }
   ]
  }
 ]
}
{
 "title": "Harvester VM Migration Details",
 "description": "Harvester VM Migration Details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_migration_data_remaining_bytes, namespace)"
    }
   },
   {
    "name": "vm",
    "label": "vm",
    "query": {
     "query": "label_values(kubevirt_vmi_migration_data_remaining_bytes, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Migration Data Remaining Bytes",
   "type": "timeseries",
   "description": "The remaining guest OS data to be migrated to the new VM.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_migration_data_remaining_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "remaining bytes"
    }
   ]
  },
  {
   "title": "Migration Data Processed Bytes",
   "type": "timeseries",
   "description": "The total Guest OS data processed and migrated to the new VM.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_migration_data_processed_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "processed bytes"
    }
   ]
  },
  {
   "title": "Migration Memory Transfer Rate",
   "type": "timeseries",
   "description": "The rate at which the memory is being transferred.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_migration_disk_transfer_rate_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "memory transfer rate"
    }
   ]
  },
  {
   "title": "Migration Dirty Memory Rate",
   "type": "timeseries",
   "description": "The rate of memory being dirty in the Guest OS.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kubevirt_vmi_migration_dirty_memory_rate_bytes{namespace=\"$namespace\", name=\"$vm\"}",
     "legendFormat": "dirty memory rate"
    }
   ]
  }
 ]
}